apps/jumpserver/urls.py
# ~*~ coding: utf-8 ~*~
from __future__ import unicode_literals

from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from .views import IndexView, LunaView, I18NView
from .swagger import get_swagger_view

api_v1 = [
   path('users/v1/', include('users.urls.api_urls', namespace='api-users')),
   path('assets/v1/', include('assets.urls.api_urls', namespace='api-assets')),
   path('perms/v1/', include('perms.urls.api_urls', namespace='api-perms')),
   path('terminal/v1/', include('terminal.urls.api_urls', namespace='api-terminal')),
   path('ops/v1/', include('ops.urls.api_urls', namespace='api-ops')),
   path('audits/v1/', include('audits.urls.api_urls', namespace='api-audits')),
   path('orgs/v1/', include('orgs.urls.api_urls', namespace='api-orgs')),
   path('settings/v1/', include('settings.urls.api_urls', namespace='api-settings')),
   path('authentication/v1/', include('authentication.urls.api_urls', namespace='api-auth')),
   path('common/v1/', include('common.urls.api_urls', namespace='api-common')),
   path('applications/v1/', include('applications.urls.api_urls', namespace='api-applications')),
]

api_v2 = [
   path('terminal/v2/', include('terminal.urls.api_urls_v2', namespace='api-terminal-v2')),
   path('users/v2/', include('users.urls.api_urls_v2', namespace='api-users-v2')),
]


app_view_patterns = [
    path('users/', include('users.urls.views_urls', namespace='users')),
    path('assets/', include('assets.urls.views_urls', namespace='assets')),
    path('perms/', include('perms.urls.views_urls', namespace='perms')),
    path('terminal/', include('terminal.urls.views_urls', namespace='terminal')),
    path('ops/', include('ops.urls.view_urls', namespace='ops')),
    path('audits/', include('audits.urls.view_urls', namespace='audits')),
    path('orgs/', include('orgs.urls.views_urls', namespace='orgs')),
    path('auth/', include('authentication.urls.view_urls'), name='auth'),
    path('applications/', include('applications.urls.views_urls', namespace='applications')),
]


if settings.XPACK_ENABLED:
    app_view_patterns.append(path('xpack/', include('xpack.urls.view_urls', namespace='xpack')))
    api_v1.append(path('xpack/v1/', include('xpack.urls.api_urls', namespace='api-xpack')))

js_i18n_patterns = i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)

api_v1_patterns = [
    path('api/', include(api_v1))
]

api_v2_patterns = [
    path('api/', include(api_v2))
]

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('', include(api_v2_patterns)),
    path('', include(api_v1_patterns)),
    path('luna/', LunaView.as_view(), name='luna-view'),
    path('i18n/<str:lang>/', I18NView.as_view(), name='i18n-switch'),
    path('settings/', include('settings.urls.view_urls', namespace='settings')),
    # path('api/v2/', include(api_v2_patterns)),

    # External apps url
    path('captcha/', include('captcha.urls')),
]

urlpatterns += app_view_patterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
            + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += js_i18n_patterns

handler404 = 'jumpserver.error_views.handler404'
handler500 = 'jumpserver.error_views.handler500'

if settings.DEBUG:
    urlpatterns += [
        re_path('^swagger(?P<format>\.json|\.yaml)$',
                get_swagger_view().without_ui(cache_timeout=1), name='schema-json'),
        path('docs/', get_swagger_view().with_ui('swagger', cache_timeout=1), name="docs"),
        path('redoc/', get_swagger_view().with_ui('redoc', cache_timeout=1), name='redoc'),

        re_path('^v2/swagger(?P<format>\.json|\.yaml)$',
                get_swagger_view().without_ui(cache_timeout=1), name='schema-json'),
        path('docs/v2/', get_swagger_view("v2").with_ui('swagger', cache_timeout=1), name="docs"),
        path('redoc/v2/', get_swagger_view("v2").with_ui('redoc', cache_timeout=1), name='redoc'),
    ]

apps/assets/models/base.py
# -*- coding: utf-8 -*-
#
import os
import uuid
from hashlib import md5

import sshpubkeys
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from common.utils import (
    get_signer, ssh_key_string_to_obj, ssh_key_gen, get_logger
)
from common.validators import alphanumeric
from orgs.mixins import OrgModelMixin
from .utils import private_key_validator

signer = get_signer()

logger = get_logger(__file__)


class AssetUser(OrgModelMixin):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    name = models.CharField(max_length=128, verbose_name=_('Name'))
    username = models.CharField(max_length=32, blank=True, verbose_name=_('Username'), validators=[alphanumeric])
    _password = models.CharField(max_length=256, blank=True, null=True, verbose_name=_('Password'))
    _private_key = models.TextField(max_length=4096, blank=True, null=True, verbose_name=_('SSH private key'), validators=[private_key_validator, ])
    _public_key = models.TextField(max_length=4096, blank=True, verbose_name=_('SSH public key'))
    comment = models.TextField(blank=True, verbose_name=_('Comment'))
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=128, null=True, verbose_name=_('Created by'))

    UNREACHABLE, REACHABLE, UNKNOWN = range(0, 3)
    CONNECTIVITY_CHOICES = (
        (UNREACHABLE, _("Unreachable")),
        (REACHABLE, _('Reachable')),
        (UNKNOWN, _("Unknown")),
    )

    @property
    def password(self):
        if self._password:
            return signer.unsign(self._password)
        else:
            return None

    @password.setter
    def password(self, password_raw):
        # raise AttributeError("Using set_auth do that")
        self._password = signer.sign(password_raw)

    @property
    def private_key(self):
        if self._private_key:
            return signer.unsign(self._private_key)

    @private_key.setter
    def private_key(self, private_key_raw):
        # raise AttributeError("Using set_auth do that")
        self._private_key = signer.sign(private_key_raw)

    @property
    def private_key_obj(self):
        if self._private_key:
            key_str = signer.unsign(self._private_key)
            return ssh_key_string_to_obj(key_str, password=self.password)
        else:
            return None

    @property
    def private_key_file(self):
        if not self.private_key_obj:
            return None
        project_dir = settings.PROJECT_DIR
        tmp_dir = os.path.join(project_dir, 'tmp')
        key_str = signer.unsign(self._private_key)
        key_name = '.' + md5(key_str.encode('utf-8')).hexdigest()
        key_path = os.path.join(tmp_dir, key_name)
        if not os.path.exists(key_path):
            self.private_key_obj.write_private_key_file(key_path)
            os.chmod(key_path, 0o400)
        return key_path

    @property
    def public_key(self):
        key = signer.unsign(self._public_key)
        if key:
            return key
        else:
            return None

    @public_key.setter
    def public_key(self, public_key_raw):
        # raise AttributeError("Using set_auth do that")
        self._public_key = signer.sign(public_key_raw)

    @property
    def public_key_obj(self):
        if self.public_key:
            try:
                return sshpubkeys.SSHKey(self.public_key)
            except TabError:
                pass
        return None

    def set_auth(self, password=None, private_key=None, public_key=None):
        update_fields = []
        if password:
            self._password = signer.sign(password)
            update_fields.append('_password')
        if private_key:
            self._private_key = signer.sign(private_key)
            update_fields.append('_private_key')
        if public_key:
            self._public_key = signer.sign(public_key)
            update_fields.append('_public_key')

        if update_fields:
            self.save(update_fields=update_fields)

    def get_auth(self, asset=None):
        pass

    def load_specific_asset_auth(self, asset):
        from ..backends.multi import AssetUserManager
        try:
            other = AssetUserManager.get(username=self.username, asset=asset)
        except Exception as e:
            logger.error(e, exc_info=True)
        else:
            self._merge_auth(other)

    def _merge_auth(self, other):
        if not other:
            return
        if other.password:
            self.password = other.password
        if other.public_key:
            self.public_key = other.public_key
        if other.private_key:
            self.private_key = other.private_key

    def clear_auth(self):
        self._password = ''
        self._private_key = ''
        self._public_key = ''
        self.save()

    def auto_gen_auth(self):
        password = str(uuid.uuid4())
        private_key, public_key = ssh_key_gen(
            username=self.username
        )
        self.set_auth(password=password,
                      private_key=private_key,
                      public_key=public_key)

    def _to_secret_json(self):
        """Push system user use it"""
        return {
            'name': self.name,
            'username': self.username,
            'password': self.password,
            'public_key': self.public_key,
            'private_key': self.private_key_file,
        }

    class Meta:
        abstract = True

apps/assets/forms/user.py
# -*- coding: utf-8 -*-
#
from django import forms
from django.utils.translation import gettext_lazy as _

from common.utils import validate_ssh_private_key, ssh_pubkey_gen, get_logger
from orgs.mixins import OrgModelForm
from ..models import AdminUser, SystemUser

logger = get_logger(__file__)
__all__ = [
    'FileForm', 'SystemUserForm', 'AdminUserForm', 'PasswordAndKeyAuthForm',
]


class FileForm(forms.Form):
    file = forms.FileField()


class PasswordAndKeyAuthForm(forms.ModelForm):
    # Form field name can not start with `_`, so redefine it,
    password = forms.CharField(
        widget=forms.PasswordInput, max_length=128,
        strip=True, required=False,
        help_text=_('Password or private key passphrase'),
        label=_("Password"),
    )
    # Need use upload private key file except paste private key content
    private_key_file = forms.FileField(required=False, label=_("Private key"))

    def clean_private_key_file(self):
        private_key_file = self.cleaned_data['private_key_file']
        password = self.cleaned_data['password']

        if private_key_file:
            key_string = private_key_file.read()
            private_key_file.seek(0)
            key_string = key_string.decode()

            if not validate_ssh_private_key(key_string, password):
                msg = _('Invalid private key, Only support '
                        'RSA/DSA format key')
                raise forms.ValidationError(msg)
        return private_key_file

    def validate_password_key(self):
        password = self.cleaned_data['password']
        private_key_file = self.cleaned_data.get('private_key_file', '')

        if not password and not private_key_file:
            raise forms.ValidationError(_(
                'Password and private key file must be input one'
            ))

    def gen_keys(self):
        password = self.cleaned_data.get('password', '') or None
        private_key_file = self.cleaned_data['private_key_file']
        public_key = private_key = None

        if private_key_file:
            private_key = private_key_file.read().strip().decode('utf-8')
            public_key = ssh_pubkey_gen(private_key=private_key, password=password)
        return private_key, public_key


class AdminUserForm(PasswordAndKeyAuthForm):
    def save(self, commit=True):
        # Because we define custom field, so we need rewrite :method: `save`
        admin_user = super().save(commit=commit)
        password = self.cleaned_data.get('password', '') or None
        private_key, public_key = super().gen_keys()
        admin_user.set_auth(password=password, public_key=public_key, private_key=private_key)
        return admin_user

    def clean(self):
        super().clean()
        if not self.instance:
            super().validate_password_key()

    class Meta:
        model = AdminUser
        fields = ['name', 'username', 'password', 'private_key_file', 'comment']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': _('Name')}),
            'username': forms.TextInput(attrs={'placeholder': _('Username')}),
        }


class SystemUserForm(OrgModelForm, PasswordAndKeyAuthForm):
    # Admin user assets define, let user select, save it in form not in view
    auto_generate_key = forms.BooleanField(initial=True, required=False)

    def save(self, commit=True):
        # Because we define custom field, so we need rewrite :method: `save`
        system_user = super().save()
        password = self.cleaned_data.get('password', '') or None
        login_mode = self.cleaned_data.get('login_mode', '') or None
        protocol = self.cleaned_data.get('protocol') or None
        auto_generate_key = self.cleaned_data.get('auto_generate_key', False)
        private_key, public_key = super().gen_keys()

        if login_mode == SystemUser.LOGIN_MANUAL or \
                protocol in [SystemUser.PROTOCOL_RDP,
                             SystemUser.PROTOCOL_TELNET,
                             SystemUser.PROTOCOL_VNC]:
            system_user.auto_push = 0
            auto_generate_key = False
            system_user.save()

        if auto_generate_key:
            logger.info('Auto generate key and set system user auth')
            system_user.auto_gen_auth()
        else:
            system_user.set_auth(password=password, private_key=private_key,
                                 public_key=public_key)

        return system_user

    def clean(self):
        super().clean()
        auto_generate = self.cleaned_data.get('auto_generate_key')
        if not self.instance and not auto_generate:
            super().validate_password_key()

    def clean_username(self):
        username = self.data.get('username')
        login_mode = self.data.get('login_mode')
        protocol = self.data.get('protocol')

        if username:
            return username
        if login_mode == SystemUser.LOGIN_AUTO and \
                protocol != SystemUser.PROTOCOL_VNC:
            msg = _('* Automatic login mode must fill in the username.')
            raise forms.ValidationError(msg)
        return username

    class Meta:
        model = SystemUser
        fields = [
            'name', 'username', 'protocol', 'auto_generate_key',
            'password', 'private_key_file', 'auto_push', 'sudo',
            'comment', 'shell', 'priority', 'login_mode', 'cmd_filters',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': _('Name')}),
            'username': forms.TextInput(attrs={'placeholder': _('Username')}),
            'cmd_filters': forms.SelectMultiple(attrs={
                'class': 'select2', 'data-placeholder': _('Command filter')
            }),
        }
        help_texts = {
            'auto_push': _('Auto push system user to asset'),
            'priority': _('1-100, High level will be using login asset as default, '
                          'if user was granted more than 2 system user'),
            'login_mode': _('If you choose manual login mode, you do not '
                            'need to fill in the username and password.'),
            'sudo': _("Use comma split multi command, ex: /bin/whoami,/bin/ifconfig")
        }

apps/templates/_base_create_update.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% block custom_head_css_js %}
    <link href="{% static 'css/plugins/select2/select2.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/plugins/select2/select2.full.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/pwstrength-bootstrap.js' %}"></script>
    {% block custom_head_css_js_create %} {% endblock %}
{% endblock %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>{{ action }}</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        {% if form.errors.all %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.errors.all }}
                            </div>
                        {% endif %}
                        {% block form %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/_foot_js.html
{% load i18n %}
{% load static %}
<!-- Mainly scripts -->
<script src="{% static "js/plugins/metisMenu/jquery.metisMenu.js" %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static "js/plugins/toastr/toastr.min.js" %}"></script>
<script src="{% static "js/inspinia.js" %}"></script>
<script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
<script src="{% static "js/jumpserver.js" %}"></script>
<script>
activeNav();
$(document).ready(function(){
    setAjaxCSRFToken();
    $('textarea').attr('rows', 5);
    if ($('.tooltip')[0]) {
        $('.tooltip').tooltip();
    }
});
</script>

apps/templates/_footer.html
{% load i18n %}
<div class="footer fixed">
    <div class="pull-right">
        Version <strong>{{ VERSION }}-{% include '_build.html' %}</strong> GPLv2.
        <!--<img style="display: none" src="http://www.jumpserver.org/img/evaluate_avatar1.jpg">-->
    </div>
    <div>
        {% include '_copyright.html' %}
    </div>
</div>

apps/templates/_head_css_js.html
{% load static %}

<!-- css file -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/sweetalert/sweetalert.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/vaildator/jquery.validator.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/datatables/datatables.min.css' %}" rel="stylesheet">
<!-- scripts -->
<script src="{% static 'js/jquery-2.1.1.js' %}"></script>
<script src="{% static 'js/plugins/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/datatables/datatables.min.js' %}"></script>

apps/templates/_header_bar.html
{% load i18n %}
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <!--<form role="search" class="navbar-form-custom" method="get" action="">-->
                <!--<div class="form-group">-->
                    <!--<input type="text" placeholder="{% trans 'Search' %}..." class="form-control" name="search" id="top-search">-->
                <!--</div>-->
            <!--</form>-->
        </div>
        <ul class="nav navbar-top-links navbar-right">
{#            <li>#}
{#                <span class="m-r-sm text-muted welcome-message">{% trans 'Welcome to use Jumpserver system' %}</span>#}
{#            </li>#}

{#            <li class="dropdown">#}
{#                <a class="count-info" href="https://market.aliyun.com/products/53690006/cmgj026011.html?spm=5176.730005.0.0.cY2io1" target="_blank">#}
{#                    <span class="m-r-sm text-muted welcome-message">{% trans 'Supports' %}</span>#}
{#                </a>#}
{#            </li>#}
{#            <li class="dropdown">#}
{#                <a class="count-info"  href="http://docs.jumpserver.org/" target="_blank">#}
{#                     <span class="m-r-sm text-muted welcome-message">{% trans 'Docs' %}</span>#}
{#                </a>#}
{#            </li>#}

            <li class="dropdown">
                <a class="count-info dropdown-toggle" data-toggle="dropdown" href="#" target="_blank">
                    <i class="fa fa-handshake-o"></i>
                    <span class="m-r-sm text-muted welcome-message">{% trans 'Help' %} <b class="caret"></b></span>
                </a>

                <ul class="dropdown-menu animated fadeInRight m-t-xs profile-dropdown">
                    <li>
                        <a class="count-info"  href="http://docs.jumpserver.org/" target="_blank">
                            <i class="fa fa-file-text"></i>
                            <span class="m-r-sm text-muted welcome-message">{% trans 'Docs' %}</span>
                        </a>
                    </li>

                </ul>

            </li>

            <li class="dropdown">
                <a class="count-info dropdown-toggle" data-toggle="dropdown" href="#" target="_blank">
                    <i class="fa fa-globe"></i>
                    {% ifequal request.COOKIES.django_language 'en' %}
                        <span class="m-r-sm text-muted welcome-message">English<b class="caret"></b></span>
                    {% else %}
                        <span class="m-r-sm text-muted welcome-message">中文<b class="caret"></b></span>
                    {% endifequal %}
                </a>

                <ul class="dropdown-menu animated fadeInRight m-t-xs profile-dropdown">
                    <li>
                        <a id="switch_cn" href="{% url 'i18n-switch' lang='zh-hans' %}">
                            <i class="fa fa-flag"></i>
                            <span> 中文</span>
                        </a>
                    </li>
                    <li>
                        <a id="switch_en" href="{% url 'i18n-switch' lang='en' %}">
                            <i class="fa fa-flag-checkered"></i>
                            <span> English</span>
                        </a>
                    </li>
                </ul>
            </li>


            <li class="dropdown">
                {% if request.user.is_authenticated %}
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="m-r-sm text-muted welcome-message">
                        <img alt="image" class="img-circle" width="30" height="30" src="{{ request.user.avatar_url }}"/>
                        <span style="font-size: 13px;font-weight: 400"> {{ request.user.name }}
                            <b class="caret"></b>
                        </span>
                    </span>
                </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs profile-dropdown">
                    <li><a href="{% url 'users:user-profile' %}"><i class="fa fa-cogs"> </i><span> {% trans 'Profile' %}</span></a></li>
                    {% if request.user.is_org_admin %}
                        {% if request.COOKIES.IN_ADMIN_PAGE == 'No' %}
                            <li><a id="switch_admin"><i class="fa fa-exchange"></i><span> {% trans 'Admin page' %}</span></a></li>
                        {% else %}
                            <li><a id="switch_user"><i class="fa fa-exchange"></i><span> {% trans 'User page' %}</span></a></li>
                        {% endif %}
                    {% endif %}
                    <li><a href="{% url 'authentication:logout' %}"><i class="fa fa-sign-out"></i> {% trans 'Logout' %}</a></li>
                </ul>
                {% else %}
                <a href="{% url 'authentication:login' %}">
                    <i class="fa fa-sign-in"></i>{% trans 'Login' %}
                </a>
                {% endif %}
            </li>
        </ul>
    </nav>
</div>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-10">
        <h2></h2>
        <ol class="breadcrumb">
            <li>
                <a href="">{% trans 'Dashboard' %}</a>
            </li>
            {% if app %}
            <li>
                <a>{{ app }}</a>
            </li>
            {% endif %}
            {% if action %}
            <li class="active">
                <strong>{{ action }}</strong>
            </li>
            {% endif %}
        </ol>
    </div>
    <div class="col-sm-2">
    </div>
</div>

apps/templates/_import_modal.html
{% extends '_modal.html' %}
{% load i18n %}

{% block modal_id %}import_modal{% endblock %}

{% block modal_confirm_id %}btn_import_confirm{% endblock %}

{% block modal_body %}
    <form method="post" id="fm_import">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label">{% trans "Download the imported template or use the exported CSV file format" %}</label>
            <a href="{% block import_modal_download_template_url %}{% endblock %}?format=csv&template=import" style="display: block">{% trans 'Download the import template' %}</a>
        </div>

        <div class="form-group">
            <label class="control-label" for="id_file">{% trans "Select the CSV file to import" %}</label>
            <input id="id_file" type="file" name="file" />
        </div>
    </form>

    <div>
        <p class="text-success" id="success_created"></p>
        <p id="success_created_detail"></p>
        <p class="text-danger" id="created_failed"></p>
        <p id="created_failed_detail"></p>
    </div>
{% endblock %}

apps/templates/_message.html
{% load i18n %}

{% block password_expired_message %}
    {% url 'users:user-password-update' as user_password_update_url %}
    {% if request.user.password_has_expired  %}
        <div class="alert alert-danger help-message alert-dismissable">
            {% blocktrans %}
                Your password has expired, please click <a href="{{ user_password_update_url }}"> this link </a> update password.
            {% endblocktrans %}
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button" style="outline: none;">×</button>
        </div>
    {% elif request.user.password_will_expired %}
        <div class="alert alert-danger help-message alert-dismissable">
            {% trans 'Your password will at' %} {{ request.user.date_password_expired }} {% trans 'expired. ' %}
            {% blocktrans %}
                please click <a href="{{ user_password_update_url }}"> this link </a> to update your password.
            {% endblocktrans %}
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button" style="outline: none;">×</button>
        </div>
    {% endif %}
{% endblock %}

{% block first_login_message %}
    {% if request.user.is_authenticated and request.user.is_first_login %}
    <div class="alert alert-danger help-message alert-dismissable">
        {% url 'users:user-first-login' as first_login_url %}
        {% blocktrans %}
        Your information was incomplete. Please click <a href="{{ first_login_url }}"> this link </a>to complete your information.
        {% endblocktrans %}
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button" style="outline: none;">×</button>
    </div>
    {% endif %}
{% endblock %}

{% block update_public_key_message %}
    {% if request.user.is_authenticated and not request.user.is_public_key_valid and not request.COOKIE.close_public_key_msg != '1' %}
    <div class="alert alert-danger help-message alert-dismissable">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button" onclick="closePublicKeyMsg()">×</button>
        {% url 'users:user-pubkey-update' as user_pubkey_update %}
        {% blocktrans %}
        Your ssh public key not set or expired. Please click <a href="{{ user_pubkey_update }}"> this link </a>to update
        {% endblocktrans %}
    </div>
    {% endif %}
{% endblock %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} help-message" >
{#            {{ message|safe }}#}
            {{ message }}
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button" style="outline: none;">×</button>
        </div>

    {% endfor %}
{% endif %}

<script>
    function closePublicKeyMsg() {
        setCookie('close_public_key_msg', 1)
    }
</script>

apps/templates/_update_modal.html
{% extends '_modal.html' %}
{% load i18n %}

{% block modal_id %}update_modal{% endblock %}

{% block modal_confirm_id %}btn_update_confirm{% endblock %}

{% block modal_body %}
    <form method="post" id="fm_import">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label">{% trans "Download the update template or use the exported CSV file format" %}</label>
            <a id="download_update_template" style="display: block">{% trans 'Download the update template' %}</a>
        </div>

        <div class="form-group">
            <label class="control-label" for="update_file">{% trans "Select the CSV file to import" %}</label>
            <input id="update_file" type="file" name="file" />
        </div>
    </form>

    <div>
        <p class="text-warning" id="success_updated"></p>
        <p id="success_updated_detail"></p>
        <p class="text-danger" id="updated_failed"></p>
        <p id="updated_failed_detail"></p>
    </div>
{% endblock %}